[package]
name = "openssl_provider_forge"
version = "0.9.0+dev"
edition = "2021"
description = "Rust crate with FFI binding for the `Core` and `Provider` APIs of `OpenSSL 3.2+`"
license = "Apache-2.0"
repository = "https://github.com/QUBIP/openssl-provider-forge-rs"
homepage = "https://qubip.eu"

[features]
# Opt-in feature to regenerate the bindings
regen = ["dep:bindgen", "dep:pkg-config"]

[dependencies]
anyhow = "1.0"
bitflags = "2.9"
crypto = { version = "0.5", features = ["std", "signature"] }
function_name = "0.3"
libc = "0.2"
log = "0.4"
num-traits = "0.2"
num_enum = "0.7"
zeroize = "1.8"

[dev-dependencies]
env_logger = "0.11"

[build-dependencies]
bindgen = { version = "0.72.1", optional = true }
pkg-config = { version = "0.3", optional = true }
