[package]
name = "openssl_provider_forge"
version = "0.8.5"
edition = "2021"
description = "Rust crate with FFI binding for the `Core` and `Provider` APIs of `OpenSSL 3.2+`"
license = "Apache-2.0"
repository = "https://github.com/QUBIP/openssl-provider-forge-rs"

[dependencies]
anyhow = "1.0.94"
bitflags = "2.6.0"
crypto = { version = "0.5.1", features = ["std", "signature"] }
function_name = "0.3"
libc = "0.2"
log = "0.4"
num-traits = "0.2"
num_enum = "0.7.3"
zeroize = "1.8.1"

[dev-dependencies]
env_logger = "0.11.6"

[build-dependencies]
bindgen = "0.72.1"
pkg-config = "0.3"
